# Generated by Django 5.2.17 on 2026-09-04 14:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization_deletion_requested_at_apikey'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('ok', models.BooleanField(default=False)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('object_key', models.CharField(blank=True, max_length=500)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger')], default='info', max_length=10)),
                ('code', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('entity_type', models.CharField(blank=True, max_length=60)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('dedupe_key', models.CharField(blank=True, max_length=200)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['org', 'read_at', 'dismissed_at'], name='core_notifi_org_id_60c9ae_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dismissed_at__isnull', True), ('read_at__isnull', True)), fields=('org', 'dedupe_key'), name='uq_notification_open_dedupe')],
            },
        ),
    ]
