# Generated by Django 5.2.17 on 2026-09-03 19:00

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('itc_eligible', models.BooleanField(default=True)),
                ('section_17_5_ref', models.CharField(blank=True, max_length=20)),
                ('tally_ledger_name', models.CharField(blank=True, max_length=100)),
                ('is_recurring_hint', models.BooleanField(default=False)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parties.expensecategory')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('vendor', 'Vendor'), ('customer', 'Customer'), ('both', 'Both')], default='vendor', max_length=10)),
                ('legal_name', models.CharField(max_length=200)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('state_code', models.CharField(blank=True, max_length=2)),
                ('pan', models.CharField(blank=True, max_length=10)),
                ('primary_email', models.EmailField(blank=True, max_length=254)),
                ('email_domains', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('is_composition', models.BooleanField(default=False)),
                ('aato_bracket', models.CharField(choices=[('below_5cr', 'Below ₹5 crore'), ('5_to_10cr', '₹5–10 crore'), ('above_10cr', 'Above ₹10 crore')], default='below_5cr', max_length=20)),
                ('payment_terms_days', models.PositiveSmallIntegerField(default=30)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('default_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parties.expensecategory')),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='parties.party')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'ordering': ['legal_name'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(fields=('org', 'name'), name='uq_category_org_name', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(condition=models.Q(('gstin__isnull', False)), fields=('org', 'gstin'), name='uq_party_gstin'),
        ),
    ]
