# Generated by Django 5.2.17 on 2026-09-04 14:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='aato_source',
            field=models.CharField(choices=[('manual', 'Set by a human'), ('inferred', 'Inferred from e-invoice IRNs')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='party',
            name='narration_aliases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=120), blank=True, default=list, size=None),
        ),
    ]
