# Generated by Django 5.2.17 on 2026-09-03 19:30

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('prompt_version', models.CharField(max_length=40)),
                ('model_name', models.CharField(max_length=60)),
                ('context_snapshot', models.JSONField(default=dict)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('proposed_attachments', models.JSONField(blank=True, default=list)),
                ('tone', models.CharField(blank=True, max_length=30)),
                ('confidence', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('guardrail_flags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, default=list, size=None)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('edited_approved', 'Edited Approved'), ('rejected', 'Rejected'), ('sent', 'Sent'), ('superseded', 'Superseded')], default='pending_review', max_length=20)),
                ('instruction', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_flags', models.JSONField(blank=True, default=list)),
                ('edit_distance', models.PositiveIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DraftRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('before', models.TextField(blank=True)),
                ('after', models.TextField(blank=True)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='mail.emaildraft')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('rfc_message_id', models.CharField(blank=True, max_length=998)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('from_address', models.EmailField(max_length=254)),
                ('to_addresses', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=254), blank=True, default=list, size=None)),
                ('cc_addresses', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=254), blank=True, default=list, size=None)),
                ('date', models.DateTimeField()),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('is_read', models.BooleanField(default=False)),
                ('injection_flag', models.BooleanField(default=False)),
                ('injection_note', models.CharField(blank=True, max_length=500)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'ordering': ['date', 'created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='emaildraft',
            name='in_reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mail.emailmessage'),
        ),
        migrations.AddField(
            model_name='emaildraft',
            name='sent_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mail.emailmessage'),
        ),
        migrations.CreateModel(
            name='EmailThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_thread_id', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('party_resolution', models.CharField(blank=True, max_length=20)),
                ('linked_invoices', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None)),
                ('intent', models.CharField(blank=True, choices=[('invoice_query', 'Invoice Query'), ('payment_confirmation', 'Payment Confirmation'), ('payment_delay_notice', 'Payment Delay Notice'), ('statement_request', 'Statement Request'), ('quote_request', 'Quote Request'), ('po_or_order', 'Po Or Order'), ('dispute', 'Dispute'), ('vendor_bill_received', 'Vendor Bill Received'), ('support', 'Support'), ('meeting_or_scheduling', 'Meeting Or Scheduling'), ('newsletter_or_spam', 'Newsletter Or Spam'), ('other', 'Other')], max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=10)),
                ('requires_finance_data', models.BooleanField(default=False)),
                ('classification_prompt_version', models.CharField(blank=True, max_length=40)),
                ('classification_model', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(choices=[('new', 'New'), ('drafted', 'Drafted'), ('awaiting_review', 'Awaiting Review'), ('replied', 'Replied'), ('closed', 'Closed'), ('ignored', 'Ignored')], default='new', max_length=20)),
                ('last_inbound_at', models.DateTimeField(blank=True, null=True)),
                ('sla_due_at', models.DateTimeField(blank=True, null=True)),
                ('snoozed_until', models.DateTimeField(blank=True, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads', to='parties.party')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mail.emailthread'),
        ),
        migrations.AddField(
            model_name='emaildraft',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='mail.emailthread'),
        ),
        migrations.CreateModel(
            name='MailboxConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('gmail', 'Gmail'), ('microsoft', 'Microsoft')], max_length=10)),
                ('email_address', models.EmailField(max_length=254)),
                ('encrypted_tokens', models.TextField(blank=True)),
                ('scopes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=120), blank=True, default=list, size=None)),
                ('status', models.CharField(choices=[('active', 'Active'), ('error', 'Error'), ('revoked', 'Revoked')], default='active', max_length=10)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('sync_cursor', models.CharField(blank=True, max_length=2000)),
                ('needs_send_scope', models.BooleanField(default=False)),
                ('connected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='emailthread',
            name='mailbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='mail.mailboxconnection'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='mailbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mail.mailboxconnection'),
        ),
        migrations.CreateModel(
            name='ReplyTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intent', models.CharField(choices=[('invoice_query', 'Invoice Query'), ('payment_confirmation', 'Payment Confirmation'), ('payment_delay_notice', 'Payment Delay Notice'), ('statement_request', 'Statement Request'), ('quote_request', 'Quote Request'), ('po_or_order', 'Po Or Order'), ('dispute', 'Dispute'), ('vendor_bill_received', 'Vendor Bill Received'), ('support', 'Support'), ('meeting_or_scheduling', 'Meeting Or Scheduling'), ('newsletter_or_spam', 'Newsletter Or Spam'), ('other', 'Other')], max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StyleGuide',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sign_off', models.CharField(blank=True, max_length=200)),
                ('tone_rules', models.TextField(blank=True)),
                ('banned_phrases', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('must_include', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('few_shot_examples', models.JSONField(blank=True, default=list)),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='style_guide', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='emaildraft',
            index=models.Index(fields=['org', 'status'], name='mail_emaild_org_id_a8dc59_idx'),
        ),
        migrations.AddConstraint(
            model_name='emaildraft',
            constraint=models.UniqueConstraint(fields=('thread', 'version'), name='uq_draft_thread_version'),
        ),
        migrations.AddConstraint(
            model_name='mailboxconnection',
            constraint=models.UniqueConstraint(fields=('org', 'provider', 'email_address'), name='uq_mailbox_org_provider_email'),
        ),
        migrations.AddIndex(
            model_name='emailthread',
            index=models.Index(fields=['org', 'status'], name='mail_emailt_org_id_4dba0f_idx'),
        ),
        migrations.AddIndex(
            model_name='emailthread',
            index=models.Index(fields=['org', 'intent'], name='mail_emailt_org_id_7f2b47_idx'),
        ),
        migrations.AddIndex(
            model_name='emailthread',
            index=models.Index(fields=['org', 'sla_due_at'], name='mail_emailt_org_id_29c63f_idx'),
        ),
        migrations.AddConstraint(
            model_name='emailthread',
            constraint=models.UniqueConstraint(fields=('mailbox', 'provider_thread_id'), name='uq_thread_mailbox_provider_id'),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['org', 'direction', 'date'], name='mail_emailm_org_id_eaf076_idx'),
        ),
        migrations.AddConstraint(
            model_name='emailmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_message_id', ''), _negated=True), fields=('mailbox', 'provider_message_id'), name='uq_message_mailbox_provider_id'),
        ),
        migrations.AddConstraint(
            model_name='replytemplate',
            constraint=models.UniqueConstraint(fields=('org', 'name'), name='uq_template_org_name'),
        ),
    ]
