# Generated by Django 5.2.17 on 2026-09-03 19:31

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('expected_date', models.DateField()),
                ('probability', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=3)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='parties.party')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FixedCashflowLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cadence', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('once', 'Once')], default='monthly', max_length=9)),
                ('next_date', models.DateField()),
                ('direction', models.CharField(choices=[('inflow', 'Inflow'), ('outflow', 'Outflow')], default='outflow', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ForecastRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('as_of', models.DateField()),
                ('horizon_days', models.PositiveSmallIntegerField()),
                ('seed', models.IntegerField()),
                ('params', models.JSONField(blank=True, default=dict)),
                ('inputs_hash', models.CharField(blank=True, max_length=64)),
                ('history_days', models.PositiveIntegerField(default=0)),
                ('insufficient_history', models.BooleanField(default=False)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('backtest_mape', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('backtest_coverage', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('backtest_n_origins', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('runway_date', models.DateField(blank=True, null=True)),
                ('narrative', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=8)),
                ('error', models.TextField(blank=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ForecastPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('p10', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('p50', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('p90', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('deterministic', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='forecasting.forecastrun')),
            ],
            options={
                'ordering': ['date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecurringExpensePattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_p50', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('period_days', models.PositiveSmallIntegerField()),
                ('next_expected', models.DateField()),
                ('confidence', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=3)),
                ('occurrences', models.PositiveSmallIntegerField(default=0)),
                ('user_confirmed', models.BooleanField(blank=True, null=True)),
                ('last_detected_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='parties.expensecategory')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='parties.party')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('overrides', models.JSONField(blank=True, default=list)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='forecastrun',
            index=models.Index(fields=['org', '-created_at'], name='forecasting_org_id_77d943_idx'),
        ),
        migrations.AddConstraint(
            model_name='forecastpoint',
            constraint=models.UniqueConstraint(fields=('run', 'date'), name='uq_forecast_point_run_date'),
        ),
        migrations.AddIndex(
            model_name='recurringexpensepattern',
            index=models.Index(fields=['org', 'next_expected'], name='forecasting_org_id_8dd1a3_idx'),
        ),
    ]
