# Generated by Django 5.2.17 on 2026-09-03 19:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.CharField(max_length=500)),
                ('sha256', models.CharField(max_length=64)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime', models.CharField(max_length=50)),
                ('size_bytes', models.PositiveIntegerField()),
                ('page_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('upload', 'Upload'), ('email', 'Email'), ('api', 'Api')], default='upload', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('extracting', 'Extracting'), ('extracted', 'Extracted'), ('failed', 'Failed'), ('superseded', 'Superseded')], default='pending', max_length=12)),
                ('error', models.TextField(blank=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('org', 'sha256'), name='uq_document_sha256')],
            },
        ),
    ]
