# Generated by Django 5.2.17 on 2026-09-03 19:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(max_length=60)),
                ('prompt_version', models.CharField(max_length=40)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('parsed', models.JSONField(blank=True, null=True)),
                ('field_confidence', models.JSONField(blank=True, default=dict)),
                ('validation_issues', models.JSONField(blank=True, default=list)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cost_inr', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='documents.document')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
