# Generated by Django 5.2.17 on 2026-09-03 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_extractionrun'),
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='source_email_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='mail.emailmessage'),
        ),
    ]
