# Generated by Django 5.2.17 on 2026-09-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_source_email_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('extracting', 'Extracting'), ('extracted', 'Extracted'), ('failed', 'Failed'), ('superseded', 'Superseded'), ('not_invoice', 'Not Invoice')], default='pending', max_length=12),
        ),
    ]
