# Generated by Django 5.2.17 on 2026-09-03 19:37

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_organization_deletion_requested_at_apikey'),
        ('invoices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTR2BBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(max_length=6)),
                ('source', models.CharField(choices=[('json', 'Json'), ('xlsx', 'Xlsx')], max_length=4)),
                ('filename', models.CharField(max_length=255)),
                ('imported_at', models.DateTimeField()),
                ('counts', models.JSONField(blank=True, default=dict)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GSTR2BRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_gstin', models.CharField(max_length=15)),
                ('supplier_name', models.CharField(blank=True, max_length=200)),
                ('invoice_number', models.CharField(max_length=32)),
                ('invoice_date', models.DateField()),
                ('invoice_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('place_of_supply', models.CharField(blank=True, max_length=2)),
                ('reverse_charge', models.BooleanField(default=False)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('igst', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cgst', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('sgst', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cess', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('itc_available', models.BooleanField(default=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('ims_action', models.CharField(blank=True, choices=[('accept', 'Accept'), ('reject', 'Reject'), ('pend', 'Pend')], max_length=6, null=True)),
                ('ims_note', models.CharField(blank=True, max_length=500)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='reconciliation.gstr2bbatch')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'ordering': ['invoice_date', 'invoice_number'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReconciliationMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_type', models.CharField(choices=[('exact', 'Exact'), ('fuzzy', 'Fuzzy'), ('value_mismatch', 'Value Mismatch'), ('missing_in_books', 'Missing In Books'), ('missing_in_2b', 'Missing In 2B')], max_length=16)),
                ('delta_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('delta_tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='reconciliation.gstr2bbatch')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='invoices.invoice')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='reconciliation.gstr2brecord')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='gstr2bbatch',
            index=models.Index(fields=['org', 'period'], name='reconciliat_org_id_e74176_idx'),
        ),
        migrations.AddIndex(
            model_name='gstr2brecord',
            index=models.Index(fields=['batch', 'supplier_gstin'], name='reconciliat_batch_i_2c1f08_idx'),
        ),
        migrations.AddIndex(
            model_name='reconciliationmatch',
            index=models.Index(fields=['batch', 'match_type'], name='reconciliat_batch_i_d77497_idx'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationmatch',
            constraint=models.UniqueConstraint(condition=models.Q(('record__isnull', False)), fields=('batch', 'record'), name='uq_match_batch_record'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationmatch',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice__isnull', False)), fields=('batch', 'invoice'), name='uq_match_batch_invoice'),
        ),
    ]
