# Generated by Django 5.2.17 on 2026-09-03 19:14

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('invoices', '0001_initial'),
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('bank', models.CharField(blank=True, max_length=100)),
                ('masked_account', models.CharField(blank=True, max_length=30)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('opening_balance_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankBalanceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('source', models.CharField(default='manual', max_length=10)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='payments.bankaccount')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankStatementImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=255)),
                ('format', models.CharField(max_length=10)),
                ('mapping', models.CharField(max_length=30)),
                ('rows_total', models.PositiveIntegerField(default=0)),
                ('rows_imported', models.PositiveIntegerField(default=0)),
                ('rows_duplicate', models.PositiveIntegerField(default=0)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='payments.bankaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('received', 'Received'), ('made', 'Made')], max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('date', models.DateField()),
                ('method', models.CharField(choices=[('neft', 'Neft'), ('upi', 'Upi'), ('cheque', 'Cheque'), ('card', 'Card'), ('cash', 'Cash'), ('other', 'Other')], default='neft', max_length=8)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='parties.party')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('sha256', models.CharField(max_length=64)),
                ('match_status', models.CharField(choices=[('unmatched', 'Unmatched'), ('auto', 'Auto'), ('manual', 'Manual'), ('ignored', 'Ignored')], default='unmatched', max_length=10)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.bankaccount')),
                ('statement_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rows', to='payments.bankstatementimport')),
                ('matched_payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_txn', to='payments.payment')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='invoices.invoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='payments.payment')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['org', 'direction', 'date'], name='payments_pa_org_id_74b33a_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['bank_account', 'match_status'], name='payments_ba_bank_ac_e0e028_idx'),
        ),
        migrations.AddConstraint(
            model_name='banktransaction',
            constraint=models.UniqueConstraint(fields=('bank_account', 'sha256'), name='uq_bank_txn_sha'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.UniqueConstraint(fields=('payment', 'invoice'), name='uq_allocation_payment_invoice'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ck_allocation_positive'),
        ),
    ]
