/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_me_retrieve"];
        put?: never;
        /** @description Switch current org: {"org_id": ...} */
        post: operations["auth_me_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Every queryset goes through TenantManager.for_org. Cross-org ids are 404, never 403. */
        get: operations["categories_list"];
        put?: never;
        /** @description Every queryset goes through TenantManager.for_org. Cross-org ids are 404, never 403. */
        post: operations["categories_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Every queryset goes through TenantManager.for_org. Cross-org ids are 404, never 403. */
        get: operations["categories_retrieve"];
        put?: never;
        post?: never;
        /** @description Every queryset goes through TenantManager.for_org. Cross-org ids are 404, never 403. */
        delete: operations["categories_destroy"];
        options?: never;
        head?: never;
        /** @description Every queryset goes through TenantManager.for_org. Cross-org ids are 404, never 403. */
        patch: operations["categories_partial_update"];
        trace?: never;
    };
    "/api/documents/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Every queryset goes through TenantManager.for_org. Cross-org ids are 404, never 403. */
        get: operations["documents_list"];
        put?: never;
        /** @description Every queryset goes through TenantManager.for_org. Cross-org ids are 404, never 403. */
        post: operations["documents_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Every queryset goes through TenantManager.for_org. Cross-org ids are 404, never 403. */
        get: operations["documents_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{id}/file/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Every queryset goes through TenantManager.for_org. Cross-org ids are 404, never 403. */
        get: operations["documents_file_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{id}/reextract/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Queue a fresh ExtractionRun; existing runs are never mutated. */
        post: operations["documents_reextract_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/bulk/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Every queryset goes through TenantManager.for_org. Cross-org ids are 404, never 403. */
        post: operations["documents_bulk_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gstins/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Every queryset goes through TenantManager.for_org. Cross-org ids are 404, never 403. */
        get: operations["gstins_list"];
        put?: never;
        /** @description Every queryset goes through TenantManager.for_org. Cross-org ids are 404, never 403. */
        post: operations["gstins_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gstins/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Every queryset goes through TenantManager.for_org. Cross-org ids are 404, never 403. */
        get: operations["gstins_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Every queryset goes through TenantManager.for_org. Cross-org ids are 404, never 403. */
        patch: operations["gstins_partial_update"];
        trace?: never;
    };
    "/api/invoices/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Every queryset goes through TenantManager.for_org. Cross-org ids are 404, never 403. */
        get: operations["invoices_list"];
        put?: never;
        /** @description Every queryset goes through TenantManager.for_org. Cross-org ids are 404, never 403. */
        post: operations["invoices_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invoices/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Every queryset goes through TenantManager.for_org. Cross-org ids are 404, never 403. */
        get: operations["invoices_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Every queryset goes through TenantManager.for_org. Cross-org ids are 404, never 403. */
        patch: operations["invoices_partial_update"];
        trace?: never;
    };
    "/api/invoices/{id}/confirm/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Every queryset goes through TenantManager.for_org. Cross-org ids are 404, never 403. */
        post: operations["invoices_confirm_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invoices/{id}/issues/{issue_id}/resolve/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Every queryset goes through TenantManager.for_org. Cross-org ids are 404, never 403. */
        post: operations["invoices_issues_resolve_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invoices/{id}/mark-duplicate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Every queryset goes through TenantManager.for_org. Cross-org ids are 404, never 403. */
        post: operations["invoices_mark_duplicate_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invoices/{id}/reject/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Every queryset goes through TenantManager.for_org. Cross-org ids are 404, never 403. */
        post: operations["invoices_reject_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invoices/bulk-confirm/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Every queryset goes through TenantManager.for_org. Cross-org ids are 404, never 403. */
        post: operations["invoices_bulk_confirm_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invoices/review-queue/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Every queryset goes through TenantManager.for_org. Cross-org ids are 404, never 403. */
        get: operations["invoices_review_queue_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Every queryset goes through TenantManager.for_org. Cross-org ids are 404, never 403. */
        get: operations["members_list"];
        put?: never;
        /** @description Every queryset goes through TenantManager.for_org. Cross-org ids are 404, never 403. */
        post: operations["members_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/members/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Every queryset goes through TenantManager.for_org. Cross-org ids are 404, never 403. */
        get: operations["members_retrieve"];
        put?: never;
        post?: never;
        /** @description Every queryset goes through TenantManager.for_org. Cross-org ids are 404, never 403. */
        delete: operations["members_destroy"];
        options?: never;
        head?: never;
        /** @description Every queryset goes through TenantManager.for_org. Cross-org ids are 404, never 403. */
        patch: operations["members_partial_update"];
        trace?: never;
    };
    "/api/orgs/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["orgs_current_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["orgs_current_partial_update"];
        trace?: never;
    };
    "/api/parties/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Every queryset goes through TenantManager.for_org. Cross-org ids are 404, never 403. */
        get: operations["parties_list"];
        put?: never;
        /** @description Every queryset goes through TenantManager.for_org. Cross-org ids are 404, never 403. */
        post: operations["parties_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/parties/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Every queryset goes through TenantManager.for_org. Cross-org ids are 404, never 403. */
        get: operations["parties_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Every queryset goes through TenantManager.for_org. Cross-org ids are 404, never 403. */
        patch: operations["parties_partial_update"];
        trace?: never;
    };
    "/api/parties/{id}/merge/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Every queryset goes through TenantManager.for_org. Cross-org ids are 404, never 403. */
        post: operations["parties_merge_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description * `below_5cr` - Below ₹5 crore
         *     * `5_to_10cr` - ₹5–10 crore
         *     * `above_10cr` - Above ₹10 crore
         * @enum {string}
         */
        AatoBracketEnum: "below_5cr" | "5_to_10cr" | "above_10cr";
        Category: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            /** Format: uuid */
            parent?: string | null;
            itc_eligible?: boolean;
            section_17_5_ref?: string;
            tally_ledger_name?: string;
            is_recurring_hint?: boolean;
            readonly is_system: boolean;
            /** Format: date-time */
            readonly created_at: string;
        };
        /**
         * @description * `inward` - Inward
         *     * `outward` - Outward
         * @enum {string}
         */
        DirectionEnum: "inward" | "outward";
        Document: {
            /** Format: uuid */
            readonly id: string;
            readonly original_filename: string;
            readonly mime: string;
            readonly size_bytes: number;
            readonly page_count: number | null;
            readonly sha256: string;
            readonly source: components["schemas"]["SourceEnum"];
            readonly status: components["schemas"]["DocumentStatusEnum"];
            readonly error: string;
            readonly attempts: number;
            /** Format: uuid */
            readonly uploaded_by: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            /** Format: uuid */
            readonly duplicate_of: string;
        };
        /**
         * @description * `pending` - Pending
         *     * `extracting` - Extracting
         *     * `extracted` - Extracted
         *     * `failed` - Failed
         *     * `superseded` - Superseded
         * @enum {string}
         */
        DocumentStatusEnum: "pending" | "extracting" | "extracted" | "failed" | "superseded";
        GSTINProfile: {
            /** Format: uuid */
            readonly id: string;
            gstin: string;
            state_code: string;
            trade_name?: string;
            registration_type?: components["schemas"]["RegistrationTypeEnum"];
            is_default?: boolean;
            /** Format: date */
            valid_from?: string | null;
            /** Format: date */
            valid_to?: string | null;
            /** Format: date-time */
            readonly created_at: string;
        };
        InvoiceDetail: {
            /** Format: uuid */
            readonly id: string;
            invoice_number: string;
            /** Format: date */
            invoice_date: string;
            /** Format: date */
            due_date?: string | null;
            direction: components["schemas"]["DirectionEnum"];
            /** Format: uuid */
            party: string;
            readonly party_name: string;
            supply_type?: components["schemas"]["SupplyTypeEnum"];
            /** Format: decimal */
            taxable_value?: string;
            /** Format: decimal */
            cgst?: string;
            /** Format: decimal */
            sgst?: string;
            /** Format: decimal */
            igst?: string;
            /** Format: decimal */
            cess?: string;
            /** Format: decimal */
            total?: string;
            /** Format: decimal */
            amount_paid?: string;
            /** Format: decimal */
            readonly outstanding: string;
            payment_status?: components["schemas"]["PaymentStatusEnum"];
            status?: components["schemas"]["StatusE97Enum"];
            validation_status?: components["schemas"]["ValidationStatusEnum"];
            /** Format: decimal */
            confidence?: string;
            fy: string;
            period_month: string;
            readonly issue_count: number;
            /** Format: date-time */
            readonly created_at: string;
            readonly lines: components["schemas"]["Line"][];
            readonly issues: components["schemas"]["Issue"][];
            /** Format: uuid */
            readonly document: string;
            /** Format: uuid */
            extraction_run?: string | null;
            /** Format: uuid */
            gstin_profile?: string | null;
            place_of_supply_state_code?: string;
            is_reverse_charge?: boolean;
            irn?: string;
            has_qr?: boolean;
            currency?: string;
            /** Format: decimal */
            round_off?: string;
            itc_eligible?: boolean;
            itc_blocked_reason?: string;
            /** Format: uuid */
            duplicate_of?: string | null;
            /** Format: uuid */
            reviewed_by?: string | null;
            /** Format: date-time */
            reviewed_at?: string | null;
            notes?: string;
            bank_details?: unknown;
            payment_terms?: string;
            layout_hash?: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        InvoiceList: {
            /** Format: uuid */
            readonly id: string;
            invoice_number: string;
            /** Format: date */
            invoice_date: string;
            /** Format: date */
            due_date?: string | null;
            direction: components["schemas"]["DirectionEnum"];
            /** Format: uuid */
            party: string;
            readonly party_name: string;
            supply_type?: components["schemas"]["SupplyTypeEnum"];
            /** Format: decimal */
            taxable_value?: string;
            /** Format: decimal */
            cgst?: string;
            /** Format: decimal */
            sgst?: string;
            /** Format: decimal */
            igst?: string;
            /** Format: decimal */
            cess?: string;
            /** Format: decimal */
            total?: string;
            /** Format: decimal */
            amount_paid?: string;
            /** Format: decimal */
            readonly outstanding: string;
            payment_status?: components["schemas"]["PaymentStatusEnum"];
            status?: components["schemas"]["StatusE97Enum"];
            validation_status?: components["schemas"]["ValidationStatusEnum"];
            /** Format: decimal */
            confidence?: string;
            fy: string;
            period_month: string;
            readonly issue_count: number;
            /** Format: date-time */
            readonly created_at: string;
        };
        InvoicePatch: {
            invoice_number?: string;
            /** Format: date */
            invoice_date?: string;
            /** Format: date */
            due_date?: string | null;
            place_of_supply_state_code?: string;
            supply_type?: components["schemas"]["SupplyTypeEnum"];
            is_reverse_charge?: boolean;
            irn?: string;
            has_qr?: boolean;
            /** Format: uuid */
            party?: string;
            itc_eligible?: boolean;
            itc_blocked_reason?: string;
            notes?: string;
            payment_terms?: string;
            lines?: components["schemas"]["LineWrite"][];
        };
        Issue: {
            /** Format: uuid */
            readonly id: string;
            code: string;
            severity: string;
            field?: string;
            message: string;
            /** Format: uuid */
            resolved_by?: string | null;
            /** Format: date-time */
            resolved_at?: string | null;
            note?: string;
        };
        /**
         * @description * `vendor` - Vendor
         *     * `customer` - Customer
         *     * `both` - Both
         * @enum {string}
         */
        KindEnum: "vendor" | "customer" | "both";
        Line: {
            /** Format: uuid */
            readonly id: string;
            line_no: number;
            description?: string;
            hsn_sac?: string;
            /** Format: decimal */
            quantity?: string;
            uom?: string;
            /** Format: decimal */
            unit_price?: string;
            /** Format: decimal */
            discount?: string;
            /** Format: decimal */
            taxable_value?: string;
            /** Format: decimal */
            rate?: string;
            /** Format: decimal */
            cess_rate?: string;
            /** Format: decimal */
            cgst?: string;
            /** Format: decimal */
            sgst?: string;
            /** Format: decimal */
            igst?: string;
            /** Format: decimal */
            cess?: string;
            /** Format: decimal */
            line_total?: string;
            /** Format: uuid */
            category?: string | null;
            /** Format: decimal */
            confidence?: string;
        };
        LineWrite: {
            /** @default  */
            description: string;
            /** @default  */
            hsn_sac: string;
            /**
             * Format: decimal
             * @default 1.000
             */
            quantity: string;
            /** @default  */
            uom: string;
            /**
             * Format: decimal
             * @default 0.00
             */
            unit_price: string;
            /**
             * Format: decimal
             * @default 0.00
             */
            discount: string;
            /**
             * Format: decimal
             * @default 0.00
             */
            rate: string;
            /**
             * Format: decimal
             * @default 0.00
             */
            cess_rate: string;
        };
        Membership: {
            /** Format: uuid */
            readonly id: string;
            /** Format: email */
            readonly email: string;
            readonly full_name: string;
            role?: components["schemas"]["RoleEnum"];
            /** Format: date-time */
            readonly created_at: string;
        };
        PaginatedCategoryList: {
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
             */
            previous?: string | null;
            results: components["schemas"]["Category"][];
        };
        PaginatedDocumentList: {
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
             */
            previous?: string | null;
            results: components["schemas"]["Document"][];
        };
        PaginatedGSTINProfileList: {
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
             */
            previous?: string | null;
            results: components["schemas"]["GSTINProfile"][];
        };
        PaginatedInvoiceListList: {
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
             */
            previous?: string | null;
            results: components["schemas"]["InvoiceList"][];
        };
        PaginatedMembershipList: {
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
             */
            previous?: string | null;
            results: components["schemas"]["Membership"][];
        };
        PaginatedPartyList: {
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
             */
            previous?: string | null;
            results: components["schemas"]["Party"][];
        };
        Party: {
            /** Format: uuid */
            readonly id: string;
            kind?: components["schemas"]["KindEnum"];
            legal_name: string;
            display_name?: string;
            gstin?: string | null;
            state_code?: string;
            pan?: string;
            primary_email?: string;
            email_domains?: string[];
            is_composition?: boolean;
            aato_bracket?: components["schemas"]["AatoBracketEnum"];
            /** Format: uuid */
            default_category?: string | null;
            payment_terms_days?: number;
            /** Format: decimal */
            credit_limit?: string | null;
            /** Format: uuid */
            readonly merged_into: string | null;
            is_active?: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        PatchedCategory: {
            /** Format: uuid */
            readonly id?: string;
            name?: string;
            /** Format: uuid */
            parent?: string | null;
            itc_eligible?: boolean;
            section_17_5_ref?: string;
            tally_ledger_name?: string;
            is_recurring_hint?: boolean;
            readonly is_system?: boolean;
            /** Format: date-time */
            readonly created_at?: string;
        };
        PatchedGSTINProfile: {
            /** Format: uuid */
            readonly id?: string;
            gstin?: string;
            state_code?: string;
            trade_name?: string;
            registration_type?: components["schemas"]["RegistrationTypeEnum"];
            is_default?: boolean;
            /** Format: date */
            valid_from?: string | null;
            /** Format: date */
            valid_to?: string | null;
            /** Format: date-time */
            readonly created_at?: string;
        };
        PatchedInvoicePatch: {
            invoice_number?: string;
            /** Format: date */
            invoice_date?: string;
            /** Format: date */
            due_date?: string | null;
            place_of_supply_state_code?: string;
            supply_type?: components["schemas"]["SupplyTypeEnum"];
            is_reverse_charge?: boolean;
            irn?: string;
            has_qr?: boolean;
            /** Format: uuid */
            party?: string;
            itc_eligible?: boolean;
            itc_blocked_reason?: string;
            notes?: string;
            payment_terms?: string;
            lines?: components["schemas"]["LineWrite"][];
        };
        PatchedMembership: {
            /** Format: uuid */
            readonly id?: string;
            /** Format: email */
            readonly email?: string;
            readonly full_name?: string;
            role?: components["schemas"]["RoleEnum"];
            /** Format: date-time */
            readonly created_at?: string;
        };
        PatchedParty: {
            /** Format: uuid */
            readonly id?: string;
            kind?: components["schemas"]["KindEnum"];
            legal_name?: string;
            display_name?: string;
            gstin?: string | null;
            state_code?: string;
            pan?: string;
            primary_email?: string;
            email_domains?: string[];
            is_composition?: boolean;
            aato_bracket?: components["schemas"]["AatoBracketEnum"];
            /** Format: uuid */
            default_category?: string | null;
            payment_terms_days?: number;
            /** Format: decimal */
            credit_limit?: string | null;
            /** Format: uuid */
            readonly merged_into?: string | null;
            is_active?: boolean;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        /**
         * @description * `unpaid` - Unpaid
         *     * `partial` - Partial
         *     * `paid` - Paid
         *     * `overdue` - Overdue
         *     * `written_off` - Written Off
         * @enum {string}
         */
        PaymentStatusEnum: "unpaid" | "partial" | "paid" | "overdue" | "written_off";
        /**
         * @description * `regular` - Regular
         *     * `composition` - Composition
         *     * `casual` - Casual
         *     * `sez` - Sez
         *     * `unregistered` - Unregistered
         * @enum {string}
         */
        RegistrationTypeEnum: "regular" | "composition" | "casual" | "sez" | "unregistered";
        /**
         * @description * `owner` - Owner
         *     * `accountant` - Accountant
         *     * `reviewer` - Reviewer
         *     * `viewer` - Viewer
         * @enum {string}
         */
        RoleEnum: "owner" | "accountant" | "reviewer" | "viewer";
        /**
         * @description * `upload` - Upload
         *     * `email` - Email
         *     * `api` - Api
         * @enum {string}
         */
        SourceEnum: "upload" | "email" | "api";
        /**
         * @description * `needs_review` - Needs Review
         *     * `confirmed` - Confirmed
         *     * `rejected` - Rejected
         *     * `duplicate` - Duplicate
         * @enum {string}
         */
        StatusE97Enum: "needs_review" | "confirmed" | "rejected" | "duplicate";
        /**
         * @description * `intra` - Intra
         *     * `inter` - Inter
         *     * `export` - Export
         *     * `sez` - Sez
         *     * `import` - Import
         * @enum {string}
         */
        SupplyTypeEnum: "intra" | "inter" | "export" | "sez" | "import";
        /**
         * @description * `valid` - Valid
         *     * `warnings` - Warnings
         *     * `invalid` - Invalid
         * @enum {string}
         */
        ValidationStatusEnum: "valid" | "warnings" | "invalid";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_me_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    categories_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedCategoryList"];
                };
            };
        };
    };
    categories_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Category"];
                "application/x-www-form-urlencoded": components["schemas"]["Category"];
                "multipart/form-data": components["schemas"]["Category"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    categories_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this expense category. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    categories_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this expense category. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    categories_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this expense category. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedCategory"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedCategory"];
                "multipart/form-data": components["schemas"]["PatchedCategory"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
        };
    };
    documents_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDocumentList"];
                };
            };
        };
    };
    documents_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Document"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
        };
    };
    documents_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this document. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
        };
    };
    documents_file_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this document. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
        };
    };
    documents_reextract_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this document. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Document"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
        };
    };
    documents_bulk_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Document"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
        };
    };
    gstins_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedGSTINProfileList"];
                };
            };
        };
    };
    gstins_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GSTINProfile"];
                "application/x-www-form-urlencoded": components["schemas"]["GSTINProfile"];
                "multipart/form-data": components["schemas"]["GSTINProfile"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GSTINProfile"];
                };
            };
        };
    };
    gstins_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this gstin profile. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GSTINProfile"];
                };
            };
        };
    };
    gstins_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this gstin profile. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedGSTINProfile"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedGSTINProfile"];
                "multipart/form-data": components["schemas"]["PatchedGSTINProfile"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GSTINProfile"];
                };
            };
        };
    };
    invoices_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedInvoiceListList"];
                };
            };
        };
    };
    invoices_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvoiceList"];
                "application/x-www-form-urlencoded": components["schemas"]["InvoiceList"];
                "multipart/form-data": components["schemas"]["InvoiceList"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceList"];
                };
            };
        };
    };
    invoices_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this invoice. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceDetail"];
                };
            };
        };
    };
    invoices_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this invoice. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedInvoicePatch"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedInvoicePatch"];
                "multipart/form-data": components["schemas"]["PatchedInvoicePatch"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoicePatch"];
                };
            };
        };
    };
    invoices_confirm_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this invoice. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvoiceList"];
                "application/x-www-form-urlencoded": components["schemas"]["InvoiceList"];
                "multipart/form-data": components["schemas"]["InvoiceList"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceList"];
                };
            };
        };
    };
    invoices_issues_resolve_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this invoice. */
                id: string;
                issue_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvoiceList"];
                "application/x-www-form-urlencoded": components["schemas"]["InvoiceList"];
                "multipart/form-data": components["schemas"]["InvoiceList"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceList"];
                };
            };
        };
    };
    invoices_mark_duplicate_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this invoice. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvoiceList"];
                "application/x-www-form-urlencoded": components["schemas"]["InvoiceList"];
                "multipart/form-data": components["schemas"]["InvoiceList"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceList"];
                };
            };
        };
    };
    invoices_reject_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this invoice. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvoiceList"];
                "application/x-www-form-urlencoded": components["schemas"]["InvoiceList"];
                "multipart/form-data": components["schemas"]["InvoiceList"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceList"];
                };
            };
        };
    };
    invoices_bulk_confirm_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvoiceList"];
                "application/x-www-form-urlencoded": components["schemas"]["InvoiceList"];
                "multipart/form-data": components["schemas"]["InvoiceList"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceList"];
                };
            };
        };
    };
    invoices_review_queue_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceList"];
                };
            };
        };
    };
    members_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedMembershipList"];
                };
            };
        };
    };
    members_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Membership"];
                "application/x-www-form-urlencoded": components["schemas"]["Membership"];
                "multipart/form-data": components["schemas"]["Membership"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Membership"];
                };
            };
        };
    };
    members_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this org membership. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Membership"];
                };
            };
        };
    };
    members_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this org membership. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    members_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this org membership. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedMembership"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedMembership"];
                "multipart/form-data": components["schemas"]["PatchedMembership"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Membership"];
                };
            };
        };
    };
    orgs_current_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    orgs_current_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    parties_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPartyList"];
                };
            };
        };
    };
    parties_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Party"];
                "application/x-www-form-urlencoded": components["schemas"]["Party"];
                "multipart/form-data": components["schemas"]["Party"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Party"];
                };
            };
        };
    };
    parties_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this party. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Party"];
                };
            };
        };
    };
    parties_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this party. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedParty"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedParty"];
                "multipart/form-data": components["schemas"]["PatchedParty"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Party"];
                };
            };
        };
    };
    parties_merge_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this party. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Party"];
                "application/x-www-form-urlencoded": components["schemas"]["Party"];
                "multipart/form-data": components["schemas"]["Party"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Party"];
                };
            };
        };
    };
}
